site_name: Ian Maurer's Notes
site_author: Ian Maurer
site_description: >-
  Personal insights on AI, genomics, and technology from Ian Maurer, CTO of GenomOncology
repo_name: Ian Maurer's Notes
repo_url: https://github.com/imaurer/blog/
site_url: https://www.imaurer.com/
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 Ian Maurer
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
      - scheme: default 
        primary: black 
        accent: deep orange
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: black
        accent: deep orange
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: medium
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      pagination_per_page: 10
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml"
  - tags
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      comments_path: "#__comments"
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - minify:
      minify_html: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: "100%"
      height: auto

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: "¶"
      title: "Table of Contents"
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - About: about.md
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/imaurer
    - icon: fontawesome/brands/github
      link: https://github.com/imaurer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ianmaurer

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 Ian Maurer
