[project]
name = "blog"
version = "0.1.0"
description = "Ian Maurer's Notes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material",
    "mkdocstrings",
    "mkdocstrings-python",
    "mkdocs-minify-plugin",
]
