authors:
  imaurer:
    name: Ian Maurer
    description: CTO @ GenomOncology
    avatar: https://github.com/imaurer.png
    social:
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/imaurer
      - icon: fontawesome/brands/github
        link: https://github.com/imaurer
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/ianmaurer